# Generated by Django 3.2.25 on 2025-04-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee')], default='customer', help_text='Select whether you are a customer or an employee.', max_length=10),
        ),
    ]
